app = "app-aknviloa"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"
  build-args = [
    "PYTHON_VERSION=3.11.7"
  ]

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  POETRY_VIRTUALENVS_CREATE = "false"
  POETRY_VERSION = "1.7.1"
  POETRY_HOME = "/opt/poetry"
  POETRY_NO_INTERACTION = "1"
  PYTHON_VERSION = "3.11.7"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
